# Generated by Django 3.2.6 on 2021-08-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_age',
            field=models.CharField(default='', max_length=2, verbose_name='Минимальный возраст учащегося'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_icon',
            field=models.ImageField(upload_to='sctionsimg/', verbose_name='Иконка курса'),
        ),
    ]
