# Generated by Django 3.2.6 on 2021-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210828_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_regularity',
            field=models.CharField(default='', max_length=1, verbose_name='Колличество уроков в неделю'),
        ),
    ]
