# Generated by Django 3.2.6 on 2021-08-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210828_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_cardItom',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_durationH',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_durationM',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_number',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_payFull',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_payMonth',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_payMonthName',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_payOnce',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_regularity',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_termMonths',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_termTimes',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_textDesc',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_textResult',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_titleModal',
        ),
    ]
