# Generated by Django 3.2.6 on 2021-08-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20210829_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_age',
            field=models.CharField(default='', max_length=2, verbose_name='Минимальный возраст учащегося'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_level',
            field=models.CharField(default='', max_length=2, verbose_name='Уровень сложности программы; от 0, до 9'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_titleCard',
            field=models.CharField(default='', max_length=20, verbose_name='Короткое название кружка'),
        ),
    ]
