# Generated by Django 3.2.6 on 2021-08-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20210829_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_durationM',
            field=models.CharField(default='', max_length=3, verbose_name='Продолжительность урока в в минутах'),
        ),
    ]
