# Generated by Django 3.2.6 on 2021-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_cmssections_cms_durationm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_number',
            field=models.CharField(default='', max_length=10, verbose_name='Колличество учащихся в группе (... - ...)'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_textDesc',
            field=models.TextField(default='', max_length=1000, verbose_name='Общая информация'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_textResult',
            field=models.TextField(default='', max_length=1000, verbose_name='Декларируемый результат'),
        ),
    ]
