# Generated by Django 3.2.6 on 2021-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20210829_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_payFull',
            field=models.CharField(default='', max_length=20, verbose_name='Полная стоимость обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonth',
            field=models.CharField(default='', max_length=10, verbose_name='Оплата за расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonthName',
            field=models.CharField(default='', max_length=20, verbose_name='Расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payOnce',
            field=models.CharField(default='', max_length=5, verbose_name='Одно занятие стоит:'),
        ),
    ]
