# Generated by Django 3.2.6 on 2021-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20210829_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_bgColor',
            field=models.CharField(default='#88C3FF', max_length=20, verbose_name='Цвет фона карточки'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_сolor',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Цвет текста карточки при наведении'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_age',
            field=models.CharField(default='-', max_length=2, verbose_name='Минимальный возраст учащегося'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_durationH',
            field=models.CharField(default='-', max_length=2, verbose_name='Продолжительность урока в академических часах'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_durationM',
            field=models.CharField(default='-', max_length=3, verbose_name='Продолжительность урока в в минутах'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_level',
            field=models.CharField(default='-', max_length=2, verbose_name='Уровень сложности программы; от 0, до 9'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_number',
            field=models.CharField(default='-', max_length=10, verbose_name='Колличество учащихся в группе (... - ...)'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_payFull',
            field=models.CharField(default='-', max_length=20, verbose_name='Полная стоимость обучения'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_payMonth',
            field=models.CharField(default='-', max_length=10, verbose_name='Оплата за расчетный месяц'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_payMonthName',
            field=models.CharField(default='-', max_length=20, verbose_name='Расчетный месяц'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_payOnce',
            field=models.CharField(default='-', max_length=5, verbose_name='Одно занятие стоит:'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_regularity',
            field=models.CharField(default='-', max_length=1, verbose_name='Колличество уроков в неделю'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_termMonths',
            field=models.CharField(default='-', max_length=2, verbose_name='Срок обучния (мес.)'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_termTimes',
            field=models.CharField(default='-', max_length=4, verbose_name='Колличество уроков в программе'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_textDesc',
            field=models.TextField(default='-', max_length=1000, verbose_name='Общая информация'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_textResult',
            field=models.TextField(default='-', max_length=1000, verbose_name='Декларируемый результат'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_titleCard',
            field=models.CharField(default='-', max_length=20, verbose_name='Короткое название кружка'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_titleModal',
            field=models.CharField(default='-', max_length=50, verbose_name='Полное название кружка'),
        ),
    ]
