# Generated by Django 3.2.6 on 2021-08-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20210829_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom',
            field=models.CharField(default='-', max_length=50, verbose_name='Пункт программы обучения'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_bgColor',
            field=models.CharField(default='#88C3FF', max_length=20, verbose_name='Цвет фона карточки (RGB/HEX)'),
        ),
        migrations.AlterField(
            model_name='cmssections',
            name='cms_сolor',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Цвет текста карточки при наведении (RGB/HEX)'),
        ),
    ]
