# Generated by Django 3.2.6 on 2021-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20210829_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_cardItom',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_payMonth',
        ),
        migrations.RemoveField(
            model_name='cmssections',
            name='cms_payMonthName',
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom1',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='1 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom10',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='10 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom2',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='2 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom3',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='3 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom4',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='4 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom5',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='5 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom6',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='6 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom7',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='7 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom8',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='8 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_cardItom9',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='9 пункт программы обучения'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonth1',
            field=models.CharField(default='-', max_length=10, verbose_name='Оплата за 1 расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonth2',
            field=models.CharField(default='-', max_length=10, verbose_name='Оплата за 2 расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonth3',
            field=models.CharField(default='-', max_length=10, verbose_name='Оплата за 3 расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonth4',
            field=models.CharField(default='-', max_length=10, verbose_name='Оплата 4 расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonthName1',
            field=models.CharField(default='-', max_length=20, verbose_name='1 расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonthName2',
            field=models.CharField(default='-', max_length=20, verbose_name='2 расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonthName3',
            field=models.CharField(default='-', max_length=20, verbose_name='3 расчетный месяц'),
        ),
        migrations.AddField(
            model_name='cmssections',
            name='cms_payMonthName4',
            field=models.CharField(default='-', max_length=20, verbose_name='4 расчетный месяц'),
        ),
    ]
