# Generated by Django 3.2.6 on 2021-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_dt', models.DateTimeField(auto_now=True)),
                ('order_fname', models.CharField(max_length=50)),
                ('order_pname', models.CharField(max_length=50)),
                ('order_lname', models.CharField(max_length=50)),
                ('order_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
