# Generated by Django 3.2.6 on 2021-08-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_dt', models.DateTimeField(auto_now=True)),
                ('enrollment_lname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('enrollment_fname', models.CharField(max_length=50, verbose_name='Имя')),
                ('enrollment_pname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('enrollment_phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'запси',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
