# Generated by Django 3.2.6 on 2021-08-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210826_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_age',
            field=models.CharField(default='', max_length=2, verbose_name='Возраст учащегося'),
        ),
    ]
