# Generated by Django 3.2.6 on 2021-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_enrollment_enrollment_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_section',
            field=models.CharField(default='', max_length=100, verbose_name='Кружок'),
        ),
    ]
