# Generated by Django 3.2.6 on 2021-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_enrollment_enrollment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_kname',
            field=models.CharField(default='', max_length=200, verbose_name='Имя учащегося'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО заказчика'),
        ),
    ]
