# Generated by Django 3.2.6 on 2021-09-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210901_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.ForeignKey(blank=True, default='новая', null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.statuscrm', verbose_name='Статус'),
        ),
    ]
